# Generated by Django 4.2 on 2024-08-23 15:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalleAv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(null=True)),
                ('numero_vivienda', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Calle/Avenida',
                'verbose_name_plural': 'Calles/Avenidas',
            },
        ),
        migrations.CreateModel(
            name='Distrito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.TextField(null=True)),
            ],
            options={
                'verbose_name': 'Distrito',
                'verbose_name_plural': 'Distritos',
            },
        ),
        migrations.CreateModel(
            name='ZonaUrb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80)),
                ('descripcion', models.TextField()),
                ('ciudad', models.CharField(default='El alto', max_length=50)),
                ('cordenadas', models.CharField(max_length=50)),
                ('distrito', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='web.distrito')),
            ],
            options={
                'verbose_name': 'Zona/Urb.',
                'verbose_name_plural': 'Zonas/Urb.',
            },
        ),
        migrations.CreateModel(
            name='Usuariosp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=50)),
                ('apellido_paterno', models.CharField(max_length=50)),
                ('apellido_materno', models.CharField(max_length=50)),
                ('codigo_usuario', models.CharField(max_length=8, unique=True)),
                ('ci', models.CharField(max_length=10)),
                ('numero_vivienda', models.IntegerField()),
                ('Calle_av', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='web.calleav')),
                ('Zona_urb', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='web.zonaurb')),
                ('grupos', models.ManyToManyField(blank=True, to='auth.group')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
            },
        ),
        migrations.CreateModel(
            name='SolicitudVecino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('foto_solicitud', models.ImageField(blank=True, upload_to='trabajo')),
                ('ubicacion_direccion', models.CharField(max_length=100)),
                ('latitud', models.FloatField(blank=True, default=-16.5, null=True)),
                ('longitud', models.FloatField(blank=True, default=-68.15, null=True)),
                ('celular', models.IntegerField()),
                ('distrito', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='web.distrito')),
                ('vecino', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='web.usuariosp')),
                ('zona_urbanizacion', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='web.zonaurb')),
            ],
            options={
                'verbose_name': 'SolicitudVecino',
                'verbose_name_plural': 'Solicitudes/Vecinos',
            },
        ),
        migrations.CreateModel(
            name='Solicitudes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('aprobado', 'Aprobado'), ('rechazado', 'Rechazado'), ('desechado', 'Desechado')], max_length=30)),
                ('asignacion', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='solicitudes_asignadas', to='web.usuariosp')),
                ('distrito', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='web.distrito')),
                ('solicitud_vecino', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='web.solicitudvecino')),
                ('zonaurb', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='web.zonaurb')),
            ],
            options={
                'verbose_name': 'Solicitud',
                'verbose_name_plural': 'Solicitudes',
            },
        ),
        migrations.CreateModel(
            name='FichaOperativa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('latitud', models.FloatField(blank=True, default=-16.5, null=True)),
                ('longitud', models.FloatField(blank=True, default=-68.15, null=True)),
                ('maquinaria', models.CharField(blank=True, max_length=50, null=True)),
                ('cuadrilla', models.CharField(max_length=100)),
                ('volumen', models.CharField(blank=True, max_length=100, null=True)),
                ('descripcion_trabajo', models.TextField(default='Descripcion...')),
                ('foto_inicio', models.ImageField(blank=True, upload_to='trabajo')),
                ('foto_desarollo', models.ImageField(blank=True, upload_to='trabajo')),
                ('foto_culminado', models.ImageField(blank=True, upload_to='trabajo')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_progreso', 'En Progreso'), ('completado', 'Completado'), ('cancelado', 'Cancelado')], default='pendiente', max_length=30)),
                ('codigo', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='web.usuariosp')),
                ('distrito', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='web.distrito')),
                ('tecnico_supervisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('zonaurb', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='web.zonaurb')),
            ],
            options={
                'verbose_name': 'Ficha Técnica',
                'verbose_name_plural': 'Fichas Técnicas',
            },
        ),
        migrations.AddField(
            model_name='calleav',
            name='zona_urb',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='web.zonaurb'),
        ),
    ]
