# Generated by Django 4.2 on 2024-08-19 01:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_distrito_fichaoperativa_zonaurb_solicitudvecino_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='calleav',
            options={'verbose_name': 'Calle/Avenida', 'verbose_name_plural': 'Calles/Avenidas'},
        ),
        migrations.AlterModelOptions(
            name='distrito',
            options={'verbose_name': 'Distrito', 'verbose_name_plural': 'Distritos'},
        ),
        migrations.AlterModelOptions(
            name='fichaoperativa',
            options={'verbose_name': 'Ficha Técnica', 'verbose_name_plural': 'Fichas Técnicas'},
        ),
        migrations.AlterModelOptions(
            name='solicitudes',
            options={'verbose_name': 'Estado de Solicitud', 'verbose_name_plural': 'Estado de Solicitudes'},
        ),
        migrations.AlterModelOptions(
            name='solicitudvecino',
            options={'verbose_name': 'SolicitudVecino', 'verbose_name_plural': 'Solicitudes/Vecinos'},
        ),
        migrations.AlterModelOptions(
            name='vecino',
            options={'verbose_name': 'Vecino', 'verbose_name_plural': 'Vecinos'},
        ),
        migrations.AlterModelOptions(
            name='zonaurb',
            options={'verbose_name': 'Zona/Urb.', 'verbose_name_plural': 'Zonas/Urb.'},
        ),
    ]
